### ISSUE TITLE
no "Monitor Services" been found, both CVM and CDB on "Data Source" dashboard

### ISSUE THREAD

**Issue by iwanchiyou** [TencentCloud/tencentcloud-monitor-grafana-app#1]
no "Monitor Services" been found
both CVM and CDB on "Data Source" dashboard

tencentcloud-monitor-grafana-app: 1.0.0
grafana: 6.1.0

**Comment by iwanchiyou** [comment]
> no "Monitor Services" been found
> both CVM and CDB on "Data Source" dashboard
> 
> tencentcloud-monitor-grafana-app: 1.0.0
> grafana: 6.1.0

well, just go to "Plugins", select tencent monitor plugin and click "update" button, I get what I want. 
never mind, please close this issue.

**Comment by susiezhao** [comment]
Monitor service is
