### ISSUE TITLE
Bug: 2.7.0 版本， mongo 预设模板 查询副本集实例No data

### ISSUE THREAD

**Issue by DBAAJ** [TencentCloud/tencentcloud-monitor-grafana-app#128]
![image](https://user-images.githubusercontent.com/39493988/183377181-e6af77f5-2cf1-4ba6-a41f-2c7fc58998fa.png)

**Comment by leonlysu** [comment]
fixed in V2.7.2, maybe published few days later

**Comment by leonlysu** [comment]
fixed in V2.7.2, maybe published few days later. thanks for the issue
