### ISSUE TITLE
无法自动获取region信息

### ISSUE THREAD

**Issue by RondoChen** [TencentCloud/tencentcloud-monitor-grafana-app#14]
![image](https://user-images.githubusercontent.com/19532861/88648281-6e0cfb00-d0f9-11ea-9fa1-77027ec98b33.png)
![image](https://user-images.githubusercontent.com/19532861/88648329-79f8bd00-d0f9-11ea-9c43-370aecdaba80.png)
如图, 使用插件自带的dashboard模板, 但是无法获取到地区信息.
使用腾讯云官方的API explorer通过POST方法可以成功获取, 怀疑是插件里面对腾讯云API调用出了问题.
请问该如何调试?

**Comment by jamesxwang** [comment]
Hi @RondoChen，欢迎使用最新版本插件体验：https://github.com/TencentCloud/tencentcloud-monitor-grafana-app/releases/latest
