### ISSUE TITLE
redis相关监控数据不支持，什么时候支持呀

### ISSUE THREAD

**Issue by lls205** [TencentCloud/tencentcloud-monitor-grafana-app#15]
1. redis相关监控数据不支持
2. cvm监控想disk相关的，在自定义图形之后获取不到数据

**Comment by chimmyhuang** [comment]
1. 最近云监控对Dashboard可视化配置和呈现能力进行了升级，原云监控插件部分特性已经在Dashboard新版中补齐或增强。体验地址：https://console.cloud.tencent.com/monitor/dashboard2/ ；

2. 近期我们正在调试基于Grafana-7.x版本的云监控插件升级，如有建议或意见，烦请留言。

**Comment by lls205** [comment]
建议新版本的插件支持获取redis相关的监控，cvm disk相关监控能插件获取图表

**Comment by jamesxwang** [comment]
@lls205 你好, Redis 相关监控数据现已在 > 1.4.1 版本中支持。
请下载 [最新版本](https://github.com/TencentCloud/tencentcloud-monitor-grafana-app/releases/latest) 体验～
