### ISSUE TITLE
Grafana-7.x版本 Period字段无法选择

### ISSUE THREAD

**Issue by sbcel9006** [TencentCloud/tencentcloud-monitor-grafana-app#16]
部署了grafana7.x版 period字段选择为空  不能正常获取数据

**Comment by cn-wx** [comment]
> 部署了grafana7.x版 period字段选择为空  不能正常获取数据

1. 这个插件是基于Grafana 6.x的，请降级Grafana版本或者使用云监控Dashboard 2.0，体验地址：https://console.cloud.tencent.com/monitor/dashboard2/
2. 近期我们正在调试基于Grafana-7.x版本的云监控插件升级，如有更新会通知您～

**Comment by sbcel9006** [comment]
感谢回复,  期待7.x的插件

**Comment by jamesxwang** [comment]
@sbcel9006 欢迎使用最新版本插件体验：https://github.com/TencentCloud/tencentcloud-monitor-grafana-app/releases/latest
