### ISSUE TITLE
CDB只展示instanceid,不展示别名

### ISSUE THREAD

**Issue by leemon9527** [TencentCloud/tencentcloud-monitor-grafana-app#18]
查看了相关的代码，是故意只展示id的吗
const CDBInstanceAliasList = ['InstanceId', 'InstanceName', 'Vip'];
// 变量替换指定实例按照那个字段展示
export const VARIABLE_ALIAS = 'instancealias'; 
const instanceAlias = CDBInstanceAliasList.indexOf(query[VARIABLE_ALIAS]) !== -1 ? query[VARIABLE_ALIAS] : 'InstanceId';

**Comment by jamesxwang** [comment]
模板变量相关可参考文档：https://cloud.tencent.com/document/product/248/54510
