### ISSUE TITLE
监控页面的前端代码直接展示了腾讯云账号的secretId和secretKey

### ISSUE THREAD

**Issue by woson-wang** [TencentCloud/tencentcloud-monitor-grafana-app#19]
在Datasource中添加了腾讯云secretId和secretKey后，在监控面板查看前端代码：
在window.grafanaBootData的settings部分，直接明文展示了secretId和secretKey
![image](https://user-images.githubusercontent.com/34298517/103497427-758cb900-4e7c-11eb-9d2d-804dbb079209.png)

**Comment by jamesxwang** [comment]
感谢反馈bug，已在[2.0](https://github.com/TencentCloud/tencentcloud-monitor-grafana-app/releases/tag/2.0.0)版本中修复，谢谢
