### ISSUE TITLE
创建变量时无法获取相应的值

### ISSUE THREAD

**Issue by junly917** [TencentCloud/tencentcloud-monitor-grafana-app#2]
非常好的一个工具，有了这个都不需要再写API来获取监控数据了. 另外是否会提供其他产品的相关内容，如mongodb、redis等产品， 希望]尽快推出， 点赞...

但是我现在遇到了以下问题：
使用模块自带可以获取到CDB数据；如下图
![image](https://user-images.githubusercontent.com/16676780/60799557-f2ff3c80-a1a5-11e9-8585-5ce4f3082cd2.png)

但是使用变量时，无法获取到相应的值?
![image](https://user-images.githubusercontent.com/16676780/60799507-d6fb9b00-a1a5-11e9-8d6c-2ef4614bdc9f.png)

Granafa的版本信息为：Grafana v6.0.2 (3f4c2e7)

**Comment by susiezhao** [comment]
非常不好意，是我们文档中介绍变量替换的文档书写出现错误，您这里拉不出来数据原因是照着我们的文档复制导致`Namespace` 复制成 `Namesapce`然后导致数据无法出来 
![image](https://user-images.githubusercontent.com/13827192/60864817-3796e080-a257-11e9-9ff6-2f17fba5e7fa.png)

**Comment by susiezhao** [comment]
关于问题中： 另外是否会提供其他产品的相关内容，如mongodb、redis等产品

这个已经在我们迭代排期中，所有腾讯云监控(https://cloud.tencent.com/document/api)上线的其他云产品我们这边都会全部提供，敬请期待；
