### ISSUE TITLE
Feature Request - Support CDN Metrics

### ISSUE THREAD

**Issue by jianzhiteh** [TencentCloud/tencentcloud-monitor-grafana-app#20]
Hi, please support CDN metrics on Grafana.

**Comment by leonlysu** [comment]
> Hi, please support CDN metrics on Grafana.
base metrics , which CDN monitor data API you want ,we need more detail about your Feature Request.
you can choose from the docs :https://cloud.tencent.com/document/api/228/43367

**Comment by leonlysu** [comment]
> Hi, please support CDN metrics on Grafana.

> Hi ,base metrics , which CDN monitor data API you want ,we need more detail about your Feature Request.
you can choose from the docs :https://cloud.tencent.com/document/api/228/43367

**Comment by leonlysu** [comment]
@jianzhiteh Hi，base metrics , which CDN monitor data API you want ,we need more detail about your Feature Request.
you can choose from the docs :https://cloud.tencent.com/document/api/228/43367

**Comment by jianzhiteh** [comment]
Hi @leonlysu , thanks for your feedback.

Here's the metrics that we are concern about CDN product - 回源数据查询

https://cloud.tencent.com/document/api/228/30986

- 回源流量（单位为 byte）
- 回源带宽（单位为 bps）
- 回源请求数（单位为 次）
- 回源失败请求数（单位为 次）
- 回源失败率（单位为 %，小数点后保留两位）
- 回源状态码 2xx 汇总及各 2 开头回源状态码明细（单位为 个）
- 回源状态码 3xx 汇总及各 3 开头回源状态码明细（单位为 个）
- 回源状态码 4xx 汇总及各 4 开头回源状态码明细（单位为 个）
- 回源状态码 5xx 汇总及各 5 开头回源状态码明细（单位为 个)

Thanks!

**Comment by jamesxwang** [comment]
@jianzhiteh Hi, CDN metrics are now supported in > 1.4.0.

Download the [latest version](https://github.com/TencentCloud/tencentcloud-monitor-grafana-app/releases/latest) is recommended.

**Comment by jianzhiteh** [comment]
Hi @jamesxwang thanks for the updates. Based on our testing, some of the metrics are hitting errors, including the following
- http_status_4xx_rate
- flux_hit_rate

An example of error (Chrome console output):
```
Error:
Code: "InvalidParameterValue"
Message: "can't find metricName=http_status_4xx_rate configure"
RequestId: "a0bd864f-74a5-4880-9549-24e99e983f9f"
```

**Comment by jamesxwang** [comment]
> Hi @jamesxwang thanks for the updates. Based on our testing, some of the metrics are hitting errors, including the following
> 
> * http_status_4xx_rate
> * flux_hit_rate
> 
> An example of error (Chrome console output):
> 
> ```
> Error:
> Code: "InvalidParameterValue"
> Message: "can't find metricName=http_status_4xx_rate configure"
> RequestId: "a0bd864f-74a5-4880-9549-24e99e983f9f"
> ```

Hi @jianzhiteh, according to your RequestId, we suggest you select `(华南地区 (广州))` as the Region and try again.
Possible reason: the `GetBaseMetric` interface under `QCE/CDN` namespace does not have region distinction.

If it works for you, please tell us and we will make some optimizations in the future.
Cheers.

**Comment by jianzhiteh** [comment]
HI @jamesxwang, I can confirm it's now working, despite of choosing `(华南地区 (广州))` or `港澳台地区(中国香港)` and other regions.

**Comment by jamesxwang** [comment]
FYI, CDN monitoring's region issue has now been fixed by defaulting `ap-guangzhou` as the region in [release 1.5.0](https://github.com/TencentCloud/tencentcloud-monitor-grafana-app/releases/tag/1.5.0).

Thank you for your love and support for our plugin, closing this issue for now.
