### ISSUE TITLE
云服务器实例，获取不到，也没有报错提示，请问怎么排查？

### ISSUE THREAD

**Issue by wanghy8166** [TencentCloud/tencentcloud-monitor-grafana-app#3]
grafana:6.2.5
配置数据源正常
获取地域正常
云服务器实例，获取不到，也没有报错提示，请问怎么排查？

**Comment by susiezhao** [comment]
https://console.cloud.tencent.com/api/explorer?Product=cvm&Version=2017-03-12&Action=DescribeInstances&SignVersion=
请优先用上面系统查一下所选择地区的云服务器实例列表，确定返回结果
![image](https://user-images.githubusercontent.com/13827192/61976682-ffe1b400-b01e-11e9-9a96-7db0a7e21d38.png)

上述返回结果正常拉取到实例信息话，请继续下面步骤：
1、 对添加的数据源进行接口连通性的测试
![image](https://user-images.githubusercontent.com/13827192/61977264-96fb3b80-b020-11e9-9825-95f91456a193.png)

2、步骤1通过后继续下面
确定是否是 limit 和 offset 的参数导致没拿到数据列表
![image](https://user-images.githubusercontent.com/13827192/61977334-c14cf900-b020-11e9-8161-afa0b65285ba.png)

如果上述方式仍没查找到问题，麻烦把相关错误贴进来，我们这边会继续跟进

**Comment by wanghy8166** [comment]
在线调用时返回结果正常

在进行"1、 对添加的数据源进行接口连通性的测试"操作时，报错提示为：
1. AuthFailure.SignatureFailure: The provided credentials could not be validated. Please check your signature is correct.
这个步骤，我在第一次提问题之前都是好的，且在线调用时也正常啊，我很奇怪为啥现在这一步不行了？

**Comment by wanghy8166** [comment]
我在腾讯云提工单，工单说tencentcloud-monitor-grafana-app是社区提供的，他们不提供支持，请问这个情况是否可以帮忙协助查看下？

**Comment by wanghy8166** [comment]
我自己又试了试，现在正常了，怀疑先前是腾讯云接口不稳定。
简单小结一下，除了要按上述步骤操作，还需要注意以下几点：
如果监控cvm的话，密钥需要有以下权限
QcloudMonitorFullAccess 	云监控（MONITOR）全读写访问权限，包括查看用户组的权限
QcloudCVMReadOnlyAccess     云服务器（CVM）相关资源只读访问权限

**Comment by zqfan** [comment]
@susiezhao 这个用户反馈的子帐号权限问题，麻烦在readme里也说明一下吧。

**Comment by susiezhao** [comment]
好的，我这边会在相关文档中进行补充
