### ISSUE TITLE
grafana连接腾讯云代理配置

### ISSUE THREAD

**Issue by feixiaohuijava** [TencentCloud/tencentcloud-monitor-grafana-app#4]
请问grafana中配置外网代理连接腾讯云是怎么设置啊？  是要在/etc/init.d/grafana-server中设置代理吗？ 我设置了没反应，想请问下作者是怎么配置外网代理的？

**Comment by susiezhao** [comment]
首先腾讯云API的访问是本身就是支持外网的，如果是外网环境是不需要配置代理的。
拿 API 文档中的 云服务器的接口来说：https://cloud.tencent.com/document/api/213/15708
你只要确保你的环境能通 cvm.tencentcloudapi.com 这个域名就可以的。
我这边需要配置外网访问是因为公司的开发环境是不支持外网的，我这边用的 Proxifier 通过配置公司提供的访问外网的域名和端口；
![image](https://user-images.githubusercontent.com/13827192/63832523-8c2b2200-c9a3-11e9-9474-55bd8968f811.png) 
然后在在 Rules 采用上述的规则让 grafana-server 的应用走我的外网代理规则
![image](https://user-images.githubusercontent.com/13827192/63832621-c694bf00-c9a3-11e9-96c2-068077dffd02.png)

**Comment by feixiaohuijava** [comment]
> 首先腾讯云API的访问是本身就是支持外网的，如果是外网环境是不需要配置代理的。
> 拿 API 文档中的 云服务器的接口来说：https://cloud.tencent.com/document/api/213/15708
> 你只要确保你的环境能通 cvm.tencentcloudapi.com 这个域名就可以的。
> 我这边需要配置外网访问是因为公司的开发环境是不支持外网的，我这边用的 Proxifier 通过配置公司提供的访问外网的域名和端口；
> ![image](https://user-images.githubusercontent.com/13827192/63832523-8c2b2200-c9a3-11e9-9474-55bd8968f811.png)
> 然后在在 Rules 采用上述的规则让 grafana-server 的应用走我的外网代理规则
> ![image](https://user-images.githubusercontent.com/13827192/63832621-c694bf00-c9a3-11e9-96c2-068077dffd02.png)

额。。我的grafana是装在linux服务器上的，我的Linux机器本身在/etc/profile设置了外网代理，但是还需要在/etc/sysconfig/grafana-server中设置代理。好坑啊，没想到grafana还要单独设置一个外网代理。我已经解决了这个问题了。哈哈。。你也可以参考https://github.com/grafana/grafana/issues/11962 这里给出了理由和答案。。
