### ISSUE TITLE
默认dashboard配置错误

### ISSUE THREAD

**Issue by kassiansun** [TencentCloud/tencentcloud-monitor-grafana-app#40]
通用问题：
1. rps/pps等频率参数默认不需要total列
2. CVM变量可以考虑使用instanceName

具体问题：
1. CVM内存使用单位错误
2. CVM外网出流量单位错误
3. Redis平均CPU使用率单位错误
4. Redis内存利用率单位错误
5. Redis连接数单位错误
6. Redis连接使用率单位错误
7. Redis入网、出网流量、使用率单位错误
8. Redis命中数单位错误

**Comment by jamesxwang** [comment]
Hi @kassiansun ，模板问题已在 PR #47 修复，已包含在版本 [1.5.0](https://github.com/TencentCloud/tencentcloud-monitor-grafana-app/releases/tag/1.5.0) 中，谢谢反馈bug！
