### ISSUE TITLE
Grafana 无法添加数据源

### ISSUE THREAD

**Issue by mkusername** [TencentCloud/tencentcloud-monitor-grafana-app#58]
grafana 7.1.5、tencentclould 2.0.2 安装均已成功，grafana也已重启，Add data source 内看不到对应的插件
![image](https://user-images.githubusercontent.com/59842288/115205825-8a8c1000-a12c-11eb-8888-b0baae404c7e.png)
![image](https://user-images.githubusercontent.com/59842288/115205913-a0013a00-a12c-11eb-82b4-01895e67df05.png)

**Comment by jamesxwang** [comment]
您好，感谢反馈bug，已确认是Grafana官方的问题，请升级Grafana版本至7.2以上，谢谢

**Comment by mkusername** [comment]
嗯，升级到7.5.4 已经解决
