### ISSUE TITLE
Unable to add datasource with error: 'Found an error in: cvm: InvalidParameter;'

### ISSUE THREAD

**Issue by KEVISONG** [TencentCloud/tencentcloud-monitor-grafana-app#60]
**Describe the bug**
When trying to add a datasource with CVM monitor on. The following error occured: 

```
Oops! Found an error in: cvm: InvalidParameter;
```

**To Reproduce**
1. Go to 'datasource'
2. Fill in secretid and secretkey
3. Enable CVM
4. Click save and test
5. See error

**Screenshots**

![image](https://user-images.githubusercontent.com/39701004/115953163-5c3b7580-a51c-11eb-9fd7-73250483bf7c.png)

**For Bug tracing (please complete the following information):**
 - `Grafana version`: v7.5.3 (3e3cf4dc60)
 - `Plugin version`: v2.0.2
 - `RequestId` in DevTools - Network tab: 71d9a70d-f7f9-40bd-9918-5baa746a06d4

**Additional context**

Complete response:

```
{"Response":{"Error":{"Code":"InvalidParameter","Message":"Url key and value should be splited by `=`."},"RequestId":"71d9a70d-f7f9-40bd-9918-5baa746a06d4"}}
```

**Comment by leonlysu** [comment]
@KEVISONG could you provide the RequestHeaders and RequestPayload of this error API？

**Comment by KEVISONG** [comment]
> @KEVISONG could you provide the RequestHeaders and RequestPayload of this error API？

@leonlysu hi, please see below : )

Request Payload:

```json
{"Offset":0,"Limit":1}
```

Request Header:

```json
POST /api/datasources/proxy/1/cvm HTTP/1.1
Host: localhost:3000
Connection: keep-alive
Content-Length: 22
sec-ch-ua: "Google Chrome";v="89", "Chromium";v="89", ";Not A Brand";v="99"
x-tc-version: 2017-03-12
x-grafana-org-id: 1
x-tc-region: ap-guangzhou
authorization: 
x-tc-requestclient: GF_7.5.3_PL_CM_2.0.2
content-type: application/json
accept: application/json, text/plain, */*
sec-ch-ua-mobile: ?0
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.114 Safari/537.36
x-grafana-nocache: true
x-tc-action: DescribeInstances
x-tc-timestamp: 1619332506
Origin: http://localhost:3000
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: cors
Sec-Fetch-Dest: empty
Referer: http://localhost:3000/datasources/edit/1/
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9,zh-CN;q=0.8,zh;q=0.7
```

**Comment by KEVISONG** [comment]
Added `tencentcloud-monitor-datasource` to `allow_loading_unsigned_plugins` solved this issue.
![image](https://user-images.githubusercontent.com/39701004/116642793-38f04a80-a9a2-11eb-87f8-dfaacd79ec40.png)
