### ISSUE TITLE
CLB负载均衡模板中修改变量无效

### ISSUE THREAD

**Issue by denkadenz** [TencentCloud/tencentcloud-monitor-grafana-app#64]
问题描述：
CLB负载均衡模板当中修改实例监听器的查询条件，将listenerAlias变量值使用ListenerName或Port无法正确获取监听器名称。返回值仍是默认ListenerId。（内外网均是如此）

![image](https://user-images.githubusercontent.com/34825741/118446217-f52b6e00-b721-11eb-8a4e-f487968301a6.png)
![image](https://user-images.githubusercontent.com/34825741/118446206-f197e700-b721-11eb-9e87-c16a2a68b1dc.png)

**Comment by xingchensly** [comment]
@denkadenz 我们会在2.1.1版本修复，谢谢反馈

**Comment by leonlysu** [comment]
@denkadenz 我们会在2.1.1版本修复，谢谢反馈

**Comment by jamesxwang** [comment]
已修复，关闭issue，如有问题可重新打开，谢谢
