### ISSUE TITLE
什么时候支持QCE/REDIS_MEM

### ISSUE THREAD

**Issue by githubzhaishuo** [TencentCloud/tencentcloud-monitor-grafana-app#68]
什么时候支持QCE/REDIS_MEM

**Comment by jamesxwang** [comment]
您好，QCE/REDIS_MEM 将在 v2.2.0中支持，待官方审核通过即可体验：[https://github.com/grafana/grafana-plugin-repository/pull/985](https://github.com/grafana/grafana-plugin-repository/pull/985)。
感谢对腾讯云监控 Grafana 插件的热爱！
