### ISSUE TITLE
Question: 获取CCNId失败

### ISSUE THREAD

**Issue by Tsukiand** [TencentCloud/tencentcloud-monitor-grafana-app#92]
**Describe your question**
腾讯云Grafana插件版本: 2.2.2
现象: grafana variable 创建获取ccnId失败 
表达式: Namespace=QCE/VBC&Action=DescribeCcns&Region=$region&InstanceAlias=CcnId

**Comment by jamesxwang** [comment]
你好，试一试这个表达式：Namespace=QCE/VBC&Action=DescribeInstances&Region=$region&InstanceAlias=CcnId

参考文档：https://cloud.tencent.com/document/product/248/54510

**Comment by Tsukiand** [comment]
> 你好，试一试这个表达式：Namespace=QCE/VBC&Action=DescribeInstances&Region=$region&InstanceAlias=CcnId
> 
> 参考文档：https://cloud.tencent.com/document/product/248/54510

谢谢 可以了

**Comment by Tsukiand** [comment]
不好意思 还有个问题项请教一下 

现在我获取了CCN的地域间的相关监控数据，文档显示 维度 CcnId, SRegion, DRegion 实际使用的时候这个维度要怎么使用？例如我在新加坡获取了CCN实例的信息，然后我获取了地域间的监控数据，但是我还想基于SRegion, DRegion展示地域间的数据。这个要如何实现

**Comment by jamesxwang** [comment]
你好，谢谢反馈，目前只支持实例维度，其他维度没有支持哦，我们会排期进行补充～

**Comment by Tsukiand** [comment]
> 



> 你好，谢谢反馈，目前只支持实例维度，其他维度没有支持哦，我们会排期进行补充～

了解 谢谢解答 后续支持会在release note里面是吧

**Comment by jamesxwang** [comment]
> > 
> 
> > 你好，谢谢反馈，目前只支持实例维度，其他维度没有支持哦，我们会排期进行补充～
> 
> 了解 谢谢解答 后续支持会在release note里面是吧

嗯嗯，会的
